project:
  type: website

website:
  title: "BNZ - Cours"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - text: Cours
        menu:
          - href: cours/obs-raisonnement-rhumato.qmd
            text: Observation & Raisonnement
          - href: cours/spondylodiscite-rhumato.qmd
            text: Spondylodiscite

format:
  html:
    theme: cosmo
    include-in-header: fontawesome.html
