project:
  type: website

website:
  title: "BNZ - Cours"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: BNZ_site.qmd
        text: Exemple

format:
  html:
    theme: cosmo
